config/routes.rb
Rails.application.routes.draw do


devise_for :users, controllers: { registrations: 'user_management/registrations' }



  post 'cart/add_to_cart/:id', to: 'cart#add_to_cart', as: 'add_to_cart'
  get 'cart/show_cart', to: 'cart#show_cart', as: 'show_cart'
  post 'cart/remove_from_cart/:book_id', to: 'cart#remove_from_cart', as: 'remove_from_cart'

  get 'onsale', to: 'books#on_sale', as:'on_sale'
  get 'newbooks', to: 'books#new_books', as:'new_books'
  get 'recently_updated', to: 'books#recently_updated', as:'recently_updated'

  get '/remove_item_from_cart/:id', to: 'books#remove_item_from_cart', as: 'remove_item_from_cart'
  post '/increase_quantity/:id', to: 'books#increase_quantity', as: 'increase_quantity'
  post '/decrease_quantity/:id', to: 'books#decrease_quantity', as: 'decrease_quantity' 


  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root 'books#index'

  resources :books do
    post 'add_to_cart', on: :member
  end

  resources :categories do
    resources :books, only: [:index]
  end

  get 'contact', to: 'contact#show'
  get 'about', to: 'about#show'

  get '/checkout', to: 'cart#checkout'
  patch 'update_province', to: 'cart#update_province'
  get '/invoice', to: 'cart#invoice', as: 'invoice'

  resources :cart, only: [] do
    collection do
      post 'checkout'
    end
  end

  resources :payments do
    collection do
      get 'success'
      get 'cancel'
    end
  end

  post 'payments/show', to: 'payments#show', as: 'show_payments'
  match '/pay/webhooks/stripe', to: 'stripe_webhooks#handle_event', via: [:get, :post] 
  post '/stripe/webhooks', to: 'stripe_webhooks#handle_event'

end

app/models/about.rb
class About < ApplicationRecord
  validates :title, presence: true, length: { maximum: 255 }
  validates :content, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["content", "created_at", "id", "id_value", "title", "updated_at"]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at",
     "reset_password_sent_at", "reset_password_token", "updated_at"]
  end

  validates :email, presence: true, uniqueness: true
  validates :encrypted_password, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :book_name, presence: true, length: { maximum: 255 }
  validates :book_desc, presence: true, length: { maximum: 255 }
  validates :book_author, presence: true, length: { maximum: 255 }
  validates :book_genre, presence: true, length: { maximum: 255 }
  validates :book_publisher, presence: true, length: { maximum: 255 }
  # validates :book_image, presence: true
  validates :category_id, presence: true
  validates :on_sale, inclusion: { in: [true, false] }

  has_one_attached :book_image
  has_and_belongs_to_many :categories, join_table:              :books_categories,
                                       association_foreign_key: :category_id
  has_one :order

  def self.ransackable_associations(auth_object = nil)
    ["book_image_attachment", "book_image_blob", "categories"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["book_author", "book_desc", "book_image", "book_name", "book_publisher", "category_id",
     "created_at", "id", "id_value", "updated_at"]
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :category_name, presence: true, length: { maximum: 255 }
  has_and_belongs_to_many :books, join_table:              :books_categories,
                                  association_foreign_key: :book_id

  def self.ransackable_associations(auth_object = nil)
    ["books"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["category_desc", "category_image", "category_name", "created_at", "id", "id_value",
     "updated_at"]
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :title, presence: true, length: { maximum: 255 }
  validates :content, presence: true
  def self.ransackable_attributes(auth_object = nil)
    ["content", "created_at", "id", "id_value", "title", "updated_at"]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
  belongs_to :province
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  enum status: { pending: 0, paid: 1, shipped: 2 }

  def self.ransackable_associations(auth_object = nil)
    ["book", "customer"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["book_id", "created_at", "customer_id", "id", "id_value", "order_id", "payment_id",
     "product_id", "province", "shipping_status", "status", "updated_at", "user"]
  end

  belongs_to :book
  belongs_to :customer
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :users
  has_many :customers
end

app/models/tax_rate.rb
class TaxRate < ApplicationRecord
end

app/models/tax_rates.rb
class TaxRates
  def self.load_rates
    YAML.load_file("#{Rails.root.join('config/tax_rates.yml')}")["tax_rates"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  pay_customer default_payment_processor: :stripe
  belongs_to :province
  has_one :customer

  def create_customer
    Customer.create(user: self)
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @category = Category.all

    @books = Book.all

    @cart = session[:cart] || {}

    if params[:filter].present?
      filters = params[:filter].split(",")
      filters.each do |filter|
        case filter
        when "on_sale"
          @books = @books.where(on_sale: true)
        when "new"
          @books = @books.where("created_at >= ?", 3.days.ago)
        when "recently_updated"
          recently_updated_books = @books.where("updated_at >= ?", 3.days.ago)
          new_books = @books.where("created_at >= ?", 3.days.ago)
          @books = recently_updated_books.where.not(id: new_books.pluck(:id))
        end
      end
    end

    if params[:search].present?
      search_term = "%#{params[:search].downcase}%"
      @books = @books.where("LOWER(book_name) LIKE ? OR LOWER(book_desc) LIKE ?", search_term,
                            search_term)
    end

    @books = @books.page(params[:page]).per(12)
  end

  def show
    @book = Book.find(params[:id])
  end

  def add_to_cart
    book = Book.find(params[:id])
    session[:cart] ||= {}
    session[:cart][book.id] ||= 0
    session[:cart][book.id] += 1
    redirect_to show_cart_path, notice: "Book added to cart successfully."
  end

  def show_cart
    @cart = session[:cart] || {}
  end

  def remove_item_from_cart
    book_id = params[:id]
    session[:cart].delete(book_id)
    redirect_to show_cart_path, notice: "Item removed from cart successfully."
  end

  def increase_quantity
    book_id = params[:id]
    session[:cart][book_id] += 1 if session[:cart][book_id]
    redirect_to show_cart_path, notice: "Quantity increased successfully."
  end

  def decrease_quantity
    book_id = params[:id]
    session[:cart][book_id] -= 1 if session[:cart][book_id] && session[:cart][book_id] > 0
    session[:cart].delete(book_id) if session[:cart][book_id] == 0
    redirect_to show_cart_path, notice: "Quantity decreased successfully."
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/views/admin/books/_category_fields.html.erb
<%= f.input :category_ids, as: :select, collection: Category.pluck(:category_name, :id), include_blank: 'Select Category', multiple: true %>

app/views/books/index.html.erb
<%= render 'shared/navbar' %>

<div class="container mx-auto py-8">
  <%= form_tag(books_path, method: "get", class: "mb-4") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search books...", class: "w-full border border-gray-300 rounded px-4 py-2" %>
    <%= submit_tag "Search", class: "mt-2 bg-blue-500 text-white px-4 py-2 rounded" %>
  <% end %>

  <% current_filters = params[:filter].to_s.split(',') %>

  <div class="flex flex-wrap justify-center my-4">
    <%= link_to "Books on Sale", books_path(filter: (current_filters + ["on_sale"]).uniq.join(',')), class: "btn btn-primary mb-2 md:mb-0 md:mr-2" unless current_filters.include?("on_sale") %>
    <%= link_to "New Books", books_path(filter: (current_filters + ["new"]).uniq.join(',')), class: "btn btn-primary mb-2 md:mb-0 md:mr-2" unless current_filters.include?("new") %>
    <%= link_to "Recently Updated Books", books_path(filter: (current_filters + ["recently_updated"]).uniq.join(',')), class: "btn btn-primary mb-2 md:mb-0 md:mr-2" unless current_filters.include?("recently_updated") %>

    <% current_filters.each do |filter| %>
      <%= button_to filter.capitalize, books_path(filter: (current_filters - [filter]).join(',')), method: :get, class: "btn btn-secondary mb-2 md:mb-0 md:mr-2" %>
    <% end %>
  </div>

  <%= link_to show_cart_path do %>
    <%= image_tag("show_cart.png", alt: "Show Cart", class: "w-[50px] h-[50px] absolute top-2 right-3") %>
  <% end %>

  <div class="flex justify-between items-center mb-4">
    <h1 class="text-3xl font-bold">All Books</h1>
  </div>

  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
    <% @books.each do |book| %>
      <div class="bg-white rounded-lg shadow-md">
        <div class="overflow-hidden rounded-t-lg">
          <% if book.book_image.attached? %>
            <%= image_tag(book.book_image, alt: "Book Cover", class: "h-[80px] w-[80px]") %>
          <% else %>
            <%= image_tag("book_cover.png", alt: "Book Cover", class: "h-[80px] w-[80px]") %>
          <% end %>
        </div>
        <div class="p-6">
          <h2 class="text-xl font-semibold mb-2">
            <%= book.book_name %>
          </h2>
          <p class="text-gray-700 mb-4">
            <%= book.book_desc %>
          </p>
          <p class="text-gray-700 mb-4 text-[20px]">
            $ <%= book.book_price %>
          </p>
          <p class="text-gray-600 mb-2">Author: <%= book.book_author %></p>
          <p class="text-gray-600 mb-2">Publisher: <%= book.book_publisher %></p>
          <p class="text-gray-600 mb-2">Genre: <%= book.book_genre %></p>
          <%= link_to "View Details", book_path(book), class: "text-blue-500 hover:underline block mb-2" %>
          <form action="<%= add_to_cart_path(book.id) %>" method="post" class="add-to-cart-form">
            <input type="hidden" name="book_id" value="<%= book.id %>">
            <input type="submit" value="Add to Cart" class="add-to-cart-button bg-blue-500 text-white px-4 py-2 rounded">
          </form>
        </div>
      </div>
    <% end %>
  </div>

  <div class="absolute top-[235px]">
    <%= paginate @books %>
  </div>
</div>

app/views/books/new_books.html.erb
<%= render 'shared/navbar' %>

<h2 class="text-2xl font-bold mb-4">New Books</h2>
<div class="grid gap-4 lg:grid-cols-3">
<div class="absolute top-10">
 <%= paginate @new_books %>
 </div>
  <% @new_books.each do |book| %>
    <div class="bg-white rounded-lg shadow-md p-4">
      <h3 class="text-xl font-semibold mb-2"><%= book.book_name %></h3>
      <p class="text-gray-700 mb-4"><%= book.book_desc %></p>
       <p class="text-gray-700 mb-4 text-[20px]">
            $ <%= book.book_price %>
          </p>
      <p class="text-gray-600 mb-2">Genre: <%= book.book_genre %></p>
          <%= link_to "View Details", book_path(book), class: "text-blue-500 hover:underline" %>
          <%= form_tag(add_to_cart_path(book.id), method: "post", class: "add-to-cart-form") do %>
            <%= hidden_field_tag :book_id, book.id %>
            <%= submit_tag "Add to Cart", class: "add-to-cart-button" %>
          <% end %>
          <% if @cart.key?(book.id) %>
            <%= link_to "Remove", remove_from_cart_path(book.id), method: :post %>
          <% end %>
    </div>
  <% end %>
</div>

app/views/books/on_sale.html.erb
<%= render 'shared/navbar' %>

<h2 class="text-2xl font-bold mb-4">Books on Sale</h2>
<div class="grid gap-4 lg:grid-cols-3">
<div class="absolute top-10">
 <%= paginate @books_on_sale %>
 </div>
  <% @books_on_sale.each do |book| %>
    <div class="bg-white rounded-lg shadow-md p-4">
      <h3 class="text-xl font-semibold mb-2"><%= book.book_name %></h3>
      <p class="text-gray-700 mb-4"><%= book.book_desc %></p>
       <p class="text-gray-700 mb-4 text-[20px]">
            $ <%= book.book_price %>
          </p>
      <p class="text-gray-600 mb-2">Genre: <%= book.book_genre %></p>
          <%= link_to "View Details", book_path(book), class: "text-blue-500 hover:underline" %>
          <%= form_tag(add_to_cart_path(book.id), method: "post", class: "add-to-cart-form") do %>
            <%= hidden_field_tag :book_id, book.id %>
            <%= submit_tag "Add to Cart", class: "add-to-cart-button" %>
          <% end %>
          <% if @cart.key?(book.id) %>
            <%= link_to "Remove", remove_from_cart_path(book.id), method: :post %>
          <% end %>
    </div>
  <% end %>
</div>

app/views/books/recently_updated.html.erb
<%= render 'shared/navbar' %>

<div class="absolute top-0  ">
 <%= paginate @recently_updated_books %>
</div>
<h2 class="text-2xl font-bold mb-4">Recently Updated Books</h2>
<div class="grid gap-4 lg:grid-cols-3">
  <% @recently_updated_books.each do |book| %>
    <div class="bg-white rounded-lg shadow-md p-4">
      <h3 class="text-xl font-semibold mb-2"><%= book.book_name %></h3>
      <p class="text-gray-700 mb-4"><%= book.book_desc %></p>
       <p class="text-gray-700 mb-4 text-[20px]">
            $ <%= book.book_price %>
          </p>
      <p class="text-gray-600 mb-2">Genre: <%= book.book_genre %></p>
          <%= link_to "View Details", book_path(book), class: "text-blue-500 hover:underline" %>
          <%= form_tag(add_to_cart_path(book.id), method: "post", class: "add-to-cart-form") do %>
            <%= hidden_field_tag :book_id, book.id %>
            <%= submit_tag "Add to Cart", class: "add-to-cart-button" %>
          <% end %>
          <% if @cart.key?(book.id) %>
            <%= link_to "Remove", remove_from_cart_path( book.id ), method: :post %>
          <% end %>
    </div>
  <% end %>
</div>

app/views/books/show.html.erb
<%= render 'shared/navbar' %>

<div class="container mx-auto py-8">
  <div class="bg-white rounded-lg shadow-md">
    <div class="overflow-hidden rounded-t-lg">
     <% if @book.book_image.present? %>
                    <%= image_tag(@book.book_image, alt: "Book Image", class: "h-[80px] w-[80px]" ) %>
                      <% else %>
                         <%= image_tag("book_cover.png", alt: "Book Image", class: "h-[80px] w-[80px]") %>
                        <% end %>
    </div>
    <div class="p-6">
      <h2 class="text-xl font-semibold mb-2"><%= @book.book_name %></h2>
      <p class="text-gray-700 mb-4"><%= @book.book_desc %></p>
       <p class="text-gray-700 mb-4 text-[20px]">
            $ <%= @book.book_price %>
          </p>
      <p class="text-gray-600 mb-2">Author: <%= @book.book_author %></p>
      <p class="text-gray-600 mb-2">Publisher: <%= @book.book_publisher %></p>
      <p class="text-gray-600 mb-2">Genre: <%= @book.book_genre %></p>
      <form action="<%= add_to_cart_path(@book.id) %>" method="post" class="add-to-cart-form">
  <input type="hidden" name="book_id" value="<%= @book.id %>">
  <input type="submit" value="Add to Cart" class="add-to-cart-button">
</form>
    </div>
  </div>
</div>