config/routes.rb
Rails.application.routes.draw do


devise_for :users, controllers: { registrations: 'user_management/registrations' }



  post 'cart/add_to_cart/:id', to: 'cart#add_to_cart', as: 'add_to_cart'
  get 'cart/show_cart', to: 'cart#show_cart', as: 'show_cart'
  post 'cart/remove_from_cart/:book_id', to: 'cart#remove_from_cart', as: 'remove_from_cart'

  get 'onsale', to: 'books#on_sale', as:'on_sale'
  get 'newbooks', to: 'books#new_books', as:'new_books'
  get 'recently_updated', to: 'books#recently_updated', as:'recently_updated'

  get '/remove_item_from_cart/:id', to: 'books#remove_item_from_cart', as: 'remove_item_from_cart'
  post '/increase_quantity/:id', to: 'books#increase_quantity', as: 'increase_quantity'
  post '/decrease_quantity/:id', to: 'books#decrease_quantity', as: 'decrease_quantity' 


  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root 'books#index'

  resources :books do
    post 'add_to_cart', on: :member
  end

  resources :categories do
    resources :books, only: [:index]
  end

  get 'contact', to: 'contact#show'
  get 'about', to: 'about#show'

  get '/checkout', to: 'cart#checkout'
  patch 'update_province', to: 'cart#update_province'
  get '/invoice', to: 'cart#invoice', as: 'invoice'

  resources :cart, only: [] do
    collection do
      post 'checkout'
    end
  end

  resources :payments do
    collection do
      get 'success'
      get 'cancel'
    end
  end

  post 'payments/show', to: 'payments#show', as: 'show_payments'
  match '/pay/webhooks/stripe', to: 'stripe_webhooks#handle_event', via: [:get, :post] 
  post '/stripe/webhooks', to: 'stripe_webhooks#handle_event'

end

app/models/about.rb
class About < ApplicationRecord
  validates :title, presence: true, length: { maximum: 255 }
  validates :content, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["content", "created_at", "id", "id_value", "title", "updated_at"]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at",
     "reset_password_sent_at", "reset_password_token", "updated_at"]
  end

  validates :email, presence: true, uniqueness: true
  validates :encrypted_password, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :book_name, presence: true, length: { maximum: 255 }
  validates :book_desc, presence: true, length: { maximum: 255 }
  validates :book_author, presence: true, length: { maximum: 255 }
  validates :book_genre, presence: true, length: { maximum: 255 }
  validates :book_publisher, presence: true, length: { maximum: 255 }
  # validates :book_image, presence: true
  validates :category_id, presence: true
  validates :on_sale, inclusion: { in: [true, false] }

  has_one_attached :book_image
  has_and_belongs_to_many :categories, join_table:              :books_categories,
                                       association_foreign_key: :category_id
  has_one :order

  def self.ransackable_associations(auth_object = nil)
    ["book_image_attachment", "book_image_blob", "categories"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["book_author", "book_desc", "book_image", "book_name", "book_publisher", "category_id",
     "created_at", "id", "id_value", "updated_at"]
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :category_name, presence: true, length: { maximum: 255 }
  has_and_belongs_to_many :books, join_table:              :books_categories,
                                  association_foreign_key: :book_id

  def self.ransackable_associations(auth_object = nil)
    ["books"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["category_desc", "category_image", "category_name", "created_at", "id", "id_value",
     "updated_at"]
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :title, presence: true, length: { maximum: 255 }
  validates :content, presence: true
  def self.ransackable_attributes(auth_object = nil)
    ["content", "created_at", "id", "id_value", "title", "updated_at"]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
  belongs_to :province
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  enum status: { pending: 0, paid: 1, shipped: 2 }

  def self.ransackable_associations(auth_object = nil)
    ["book", "customer"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["book_id", "created_at", "customer_id", "id", "id_value", "order_id", "payment_id",
     "product_id", "province", "shipping_status", "status", "updated_at", "user"]
  end

  belongs_to :book
  belongs_to :customer
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :users
  has_many :customers
end

app/models/tax_rate.rb
class TaxRate < ApplicationRecord
end

app/models/tax_rates.rb
class TaxRates
  def self.load_rates
    YAML.load_file("#{Rails.root.join('config/tax_rates.yml')}")["tax_rates"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  pay_customer default_payment_processor: :stripe
  belongs_to :province
  has_one :customer

  def create_customer
    Customer.create(user: self)
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def add_to_cart
    book = Book.find(params[:id])
    session[:cart] ||= {}
    session[:cart][book.id] ||= 0
    session[:cart][book.id] += 1
    redirect_to show_cart_path, notice: "Book added to cart successfully."
  end

  def show_cart
    @cart = session[:cart] || {}
  end

  def remove_from_cart
    book_id = params[:book_id].to_i
    session[:cart].delete(book_id) if session[:cart].key?(book_id)

    redirect_to show_cart_path, notice: "Book removed from cart successfully."
  end

  def update_province
    @cart = session[:cart] || {}

    @user = current_user
    if @user.update(user_params)
      flash[:success] = "Province updated successfully."
      session[:cart] = @cart
    else
      flash[:error] = "Failed to update province."
    end
    redirect_to invoice_path
  end

  def user_params
    params.require(:user).permit(:province_id)
  end

  def invoice
    if current_user
      @user = current_user
      @cart = session[:cart] || {}
      @total_price = calculate_total_price(@cart)
      @province_id = @user.province_id
      @province_name = Province.find(@province_id).name
      @tax_rates = TaxRates.load_rates[@province_name]
      @book = Book.find(@cart.keys.first) unless @cart.empty?

      if @tax_rates.nil?
        flash.now[:error] = "Tax rates for your province are not found. Please contact support."
        return
      end

      @pst_rate = @tax_rates["pst"]
      @gst_rate = @tax_rates["gst"]
      @hst_rate = @tax_rates["hst"]
      @pst_amount = @total_price * @pst_rate
      @gst_amount = @total_price * @gst_rate
      @hst_amount = @total_price * @hst_rate
      @total_with_taxes = @total_price + @pst_amount + @gst_amount + @hst_amount
    else
      flash.now[:error] = "You must be logged in to view the invoice."
    end
  end

  private

  def calculate_total_price(cart)
    total_price = 0
    cart.each do |book_id, quantity|
      book = Book.find(book_id)
      total_price += book.book_price * quantity
    end
    total_price
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/views/cart/add_to_cart.html.erb
<%= render 'shared/navbar' %>

<div>
  <h1 class="font-bold text-4xl">Cart#add_to_cart</h1>
  <p>Find me in app/views/cart/add_to_cart.html.erb</p>
</div>

app/views/cart/checkout.html.erb
<%= render 'shared/navbar' %>

<div class="container mx-auto py-8">
  <h1 class="text-3xl font-bold mb-6">Checkout</h1>

  <% if @cart.present? %>
    <div class="bg-white shadow-md rounded-lg p-6 mb-6">
      <h2 class="text-xl font-semibold mb-4">Shopping Cart</h2>
      <% @cart.each do |book_id, quantity| %>
        <% book = Book.find(book_id) %>
        <div class="flex items-center border-b border-gray-200 py-4">
          <div class="ml-4 flex-1">
            <h3 class="font-semibold text-lg"><%= book.book_name %></h3>
            <p class="text-gray-600">Quantity: <%= quantity %></p>
          </div>
        </div>
      <% end %>
    </div>

    <div class="bg-white shadow-md rounded-lg p-6 mb-6">
      <h2 class="text-xl font-semibold mb-4">Invoice</h2>
      <p class="mb-2"><strong>Total Price:</strong> <%= number_to_currency(@total_price) %></p>
      <% if @pst_amount.present? && @pst_amount.positive? %>
        <p class="mb-2"><strong>Tax (PST):</strong> <%= number_to_currency(@pst_amount) %></p>
      <% end %>
      <% if @gst_amount.present? && @gst_amount.positive? %>
        <p class="mb-2"><strong>Tax (GST):</strong> <%= number_to_currency(@gst_amount) %></p>
      <% end %>
      <% if @hst_amount.present? && @hst_amount.positive? %>
        <p class="mb-2"><strong>Tax (HST):</strong> <%= number_to_currency(@hst_amount) %></p>
      <% end %>
      <p class="mb-2"><strong>Total with Tax:</strong> <%= number_to_currency(@total_with_taxes) %></p>
    </div>
  <% else %>
    <p class="text-gray-700">Your shopping cart is empty</p>
  <% end %>
</div>

app/views/cart/invoice.html.erb
<%= render 'shared/navbar' %>

<div class="container mx-auto py-8">
  <h1 class="text-3xl font-bold mb-6">Checkout</h1>

  <% if @cart.present? %>
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6"> 
      <div class="bg-white shadow-md rounded-lg p-6">
        <h2 class="text-xl font-semibold mb-4">Order Details</h2>
        <% @cart.each do |book_id, quantity| %>
          <% book = Book.find(book_id) %>
          <div class="flex items-center border-b border-gray-200 py-4">
            <div class="ml-4 flex-1">
              <h3 class="font-semibold text-lg"><%= book.book_name %></h3>
              <p class="text-gray-600">Quantity: <%= quantity %></p>
            </div>
          </div>
        <% end %>
      </div>

      <div class="bg-white shadow-md rounded-lg p-6">
        <h2 class="text-xl font-semibold mb-4">Invoice</h2>
        <p class="mb-2 text-[20px]"><strong>Total Price:</strong> <%= number_to_currency(@total_price) %></p>
        <% if @pst_amount.present? && @pst_amount.positive? %>
          <p class="mb-2 text-[20px]"><strong>Tax (PST):</strong> <%= number_to_currency(@pst_amount) %></p>
        <% end %>
        <% if @gst_amount.present? && @gst_amount.positive? %>
          <p class="mb-2 text-[20px]"><strong>Tax (GST):</strong> <%= number_to_currency(@gst_amount) %></p>
        <% end %>
        <% if @hst_amount.present? && @hst_amount.positive? %>
          <p class="mb-2 text-[20px]"><strong>Tax (HST):</strong> <%= number_to_currency(@hst_amount) %></p>
        <% end %>
        <p class="mb-2 text-[20px]"><strong>Total with Tax:</strong> <%= number_to_currency(@total_with_taxes) %></p>
      </div>
    </div><br>

    <div class="bg-white shadow-md rounded-lg p-6">
      <h2 class="text-xl font-semibold mb-4">Update Province</h2>
      <form action="<%= update_province_path %>" method="post">
        <input type="hidden" name="_method" value="patch">
        <div class="mb-4">
          <label for="user_province_id" class="block text-gray-700 font-bold mb-2">Province</label>
          <select name="user[province_id]" id="user_province_id" class="block appearance-none w-full bg-white border border-gray-400 hover:border-gray-500 px-4 py-2 rounded shadow">
            <option value="" <% unless @user.province_id %>selected<% end %> disabled>Select Province</option>
            <% Province.all.each do |province| %>
              <option value="<%= province.id %>" <%= 'selected' if @user.province_id == province.id %>><%= province.name %></option>
            <% end %>
          </select>
        </div>

        <div class="flex items-center">
          <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Update Province</button>
        </div>
      </form>
    </div>

    <div class="flex justify-end">
      <%= link_to 'Proceed to checkout', show_payments_path(book_id: @book.id), class: "bg-blue-500 hover:bg-blue-700 text-black font-bold py-2 px-4 rounded-full shadow-md" %>
    </div>

  <% else %>
    <p class="text-gray-700">Your shopping cart is empty.</p>
  <% end %>
</div>

app/views/cart/show_cart.html.erb
<%= render 'shared/navbar' %>

<%= link_to root_path do %>
  <%= image_tag("home.png", alt: "Show Cart", class: "w-[50px] h-[50px] absolute top-2 left-2") %>
<% end %>

  <% if @cart.present? %>
<div class="container mx-auto py-8">
  <h1 class="text-3xl font-bold mb-6">Shopping Cart</h1>
   <%= link_to "Checkout", invoice_path, class: "bg-blue-500 hover:bg-blue-700 text-black font-bold py-2 px-4 rounded-full shadow-md" %>
<br>
    <div class="shopping-cart">
      <% @cart.each do |book_id, quantity| %>
        <% book = Book.find(book_id) %>
        <div class="bg-white rounded-lg shadow-md p-6">
          <h2 class="text-xl font-semibold mb-2"><%= book.book_name %></h2>
          <p class="text-gray-700 mb-2"><%= book.book_desc %></p>
          <p class="text-gray-600">Quantity: <%= quantity %></p>
          
          <div class="quantity-buttons mt-4">
            <div class="flex">
              <form action="<%= increase_quantity_path(book_id) %>" method="post">
  <button type="submit" class="increase">+</button>
</form>

              
              <form action="<%= decrease_quantity_path(book_id) %>" method="post">
  <button type="submit" class="decrease">-</button>
</form>

            </div>
            
            <%= link_to "Remove", remove_item_from_cart_path(book_id), method: :post, data: { confirm: 'Are you sure you want to remove this item from your cart?' }, class: "remove-link" %>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p class="text-gray-700">Your shopping cart is empty.</p>
  <% end %>
</div>