config/routes.rb
Rails.application.routes.draw do


devise_for :users, controllers: { registrations: 'user_management/registrations' }



  post 'cart/add_to_cart/:id', to: 'cart#add_to_cart', as: 'add_to_cart'
  get 'cart/show_cart', to: 'cart#show_cart', as: 'show_cart'
  post 'cart/remove_from_cart/:book_id', to: 'cart#remove_from_cart', as: 'remove_from_cart'

  get 'onsale', to: 'books#on_sale', as:'on_sale'
  get 'newbooks', to: 'books#new_books', as:'new_books'
  get 'recently_updated', to: 'books#recently_updated', as:'recently_updated'

  get '/remove_item_from_cart/:id', to: 'books#remove_item_from_cart', as: 'remove_item_from_cart'
  post '/increase_quantity/:id', to: 'books#increase_quantity', as: 'increase_quantity'
  post '/decrease_quantity/:id', to: 'books#decrease_quantity', as: 'decrease_quantity' 


  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root 'books#index'

  resources :books do
    post 'add_to_cart', on: :member
  end

  resources :categories do
    resources :books, only: [:index]
  end

  get 'contact', to: 'contact#show'
  get 'about', to: 'about#show'

  get '/checkout', to: 'cart#checkout'
  patch 'update_province', to: 'cart#update_province'
  get '/invoice', to: 'cart#invoice', as: 'invoice'

  resources :cart, only: [] do
    collection do
      post 'checkout'
    end
  end

  resources :payments do
    collection do
      get 'success'
      get 'cancel'
    end
  end

  post 'payments/show', to: 'payments#show', as: 'show_payments'
  match '/pay/webhooks/stripe', to: 'stripe_webhooks#handle_event', via: [:get, :post] 
  post '/stripe/webhooks', to: 'stripe_webhooks#handle_event'

end

app/models/about.rb
class About < ApplicationRecord
  validates :title, presence: true, length: { maximum: 255 }
  validates :content, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["content", "created_at", "id", "id_value", "title", "updated_at"]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at",
     "reset_password_sent_at", "reset_password_token", "updated_at"]
  end

  validates :email, presence: true, uniqueness: true
  validates :encrypted_password, presence: true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :book_name, presence: true, length: { maximum: 255 }
  validates :book_desc, presence: true, length: { maximum: 255 }
  validates :book_author, presence: true, length: { maximum: 255 }
  validates :book_genre, presence: true, length: { maximum: 255 }
  validates :book_publisher, presence: true, length: { maximum: 255 }
  # validates :book_image, presence: true
  validates :category_id, presence: true
  validates :on_sale, inclusion: { in: [true, false] }

  has_one_attached :book_image
  has_and_belongs_to_many :categories, join_table:              :books_categories,
                                       association_foreign_key: :category_id
  has_one :order

  def self.ransackable_associations(auth_object = nil)
    ["book_image_attachment", "book_image_blob", "categories"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["book_author", "book_desc", "book_image", "book_name", "book_publisher", "category_id",
     "created_at", "id", "id_value", "updated_at"]
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :category_name, presence: true, length: { maximum: 255 }
  has_and_belongs_to_many :books, join_table:              :books_categories,
                                  association_foreign_key: :book_id

  def self.ransackable_associations(auth_object = nil)
    ["books"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["category_desc", "category_image", "category_name", "created_at", "id", "id_value",
     "updated_at"]
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :title, presence: true, length: { maximum: 255 }
  validates :content, presence: true
  def self.ransackable_attributes(auth_object = nil)
    ["content", "created_at", "id", "id_value", "title", "updated_at"]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
  belongs_to :province
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  enum status: { pending: 0, paid: 1, shipped: 2 }

  def self.ransackable_associations(auth_object = nil)
    ["book", "customer"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["book_id", "created_at", "customer_id", "id", "id_value", "order_id", "payment_id",
     "product_id", "province", "shipping_status", "status", "updated_at", "user"]
  end

  belongs_to :book
  belongs_to :customer
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :users
  has_many :customers
end

app/models/tax_rate.rb
class TaxRate < ApplicationRecord
end

app/models/tax_rates.rb
class TaxRates
  def self.load_rates
    YAML.load_file("#{Rails.root.join('config/tax_rates.yml')}")["tax_rates"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  pay_customer default_payment_processor: :stripe
  belongs_to :province
  has_one :customer

  def create_customer
    Customer.create(user: self)
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalRails</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "rails-ujs" %>
<script src="https://js.stripe.com/v3/"></script>
  </head>

  <body class="">
    <div class="container mx-auto px-4">
      <div class="py-6">
        <h2 class="text-green-600 absolute left-[40%]"><%= notice %></h2>
        <h2 class="text-red-600 absolute left-[40%]"><%= alert %></h2>`

        <% if user_signed_in? %>
          <div class="mt-4">
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "text-balck-500 bg-red-500 hover:bg-red-600 text-white py-2 px-4 rounded absolute right-20 top-4" %>
          </div>
        <% else %>
          <div class="mt-4">
            <%= link_to "Sign up", new_user_registration_path, class: "text-black-100 bg-blue-500 hover:bg-blue-600 text-white py-2 px-4 rounded absolute right-20 top-4 rounded-full" %>
            <%= link_to "Login", new_user_session_path, class: "text-black-100 bg-blue-500 hover:bg-blue-600 text-white py-2 px-4 rounded absolute right-[180px] top-4 rounded-full" %>
          </div>
        <% end %>
      </div>

        <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="flex items-center">
  <%= link_to root_path do %>
        <%= image_tag("home.png", alt: "Show Cart", class: "w-[50px] h-[50px] absolute top-2 left-2 sm:w-[50px] sm:[50px]") %>
  <% end %>
  <div class="flex">
    <%= link_to "About", about_path, class: "text-gray-300 px-3 py-2 rounded-md text-base font-medium sm:text-md" %>
    <%= link_to "Contact", contact_path, class: "text-gray-300 px-3 py-2 rounded-md text-base font-medium sm:text-sm" %>
    <%= link_to "Shop", books_path, class: "text-gray-300 px-3 py-2 rounded-md text-base font-medium sm:text-sm" %>
    <%= link_to "Cart", show_cart_path, class: "text-gray-300 px-3 py-2 rounded-md text-base font-medium sm:text-sm" %>
  </div>
</nav>